//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Team_Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        internal string GameName;

        public int GameID { get; set; }
        public string GameDescription { get; set; }
        public string TotalPoints { get; set; }
        public int Spectators { get; set; }
        public string WinningTeam { get; set; }
    }
}
