//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Team_Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamName { get; set; }
        public int TeamID { get; set; }
        public string TeamDescription { get; set; }
        public int PointsScored { get; set; }
        public int PointsLost { get; set; }
    }
}
